version: '3.9'

services:
  backend:
    container_name: 'backend_container'
    volumes:
      - ./backend/src:/backend/src
    build:
      context: ./backend
      args:
        - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/stock-profit-api-test
      - MAX_WORKERS_THREADS=4